name: 'gradle-unused-resources-action'
description: 'Action to run `gradle-unused-resources-remover-plugin`'
author: '@HedvigInsurance'
inputs:
  root-build-gradle-file:
    description: "The path to the root `build.gradle{.kts}`-file of your project."
    required: false
    default: 'build.gradle.kts'
  skip-plugin:
    description: "Set to true to not have the action temporarily add the plugin before attempting to run."
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
